#!/usr/bin/env python3
"""Laptop gateway for the Arduino -> Pi traffic testbed.

The gateway reads real IMU samples from the Arduino over USB serial, wraps each
sample in a local HTTP request, and controls the request timing pattern.
Use --mock-sensor when the Arduino is not connected yet.
"""

from __future__ import annotations

import argparse
import json
import math
import random
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any, Optional


DEFAULT_RATES = {
    "normal": 4.0,
    "burst": 14.0,
    "attack_like": 35.0,
}


@dataclass
class SensorSample:
    """One IMU sample read from the Arduino or generated by the mock sensor."""
    seq: int
    t_ms: int
    ax: float
    ay: float
    az: float
    gx: float
    gy: float
    gz: float
    source: str = "mock"

    def to_dict(self) -> dict[str, Any]:
        return {
            "seq": self.seq,
            "t_ms": self.t_ms,
            "ax": self.ax,
            "ay": self.ay,
            "az": self.az,
            "gx": self.gx,
            "gy": self.gy,
            "gz": self.gz,
            "source": self.source,
        }


class ArduinoReader:
    """Non-blocking serial reader that keeps the latest valid Arduino JSON sample."""

    def __init__(self, port: str, baud: int) -> None:
        try:
            import serial  # type: ignore
        except ImportError as exc:
            raise SystemExit(
                "pyserial is required for Arduino mode. Install it with: python -m pip install pyserial"
            ) from exc

        self.serial = serial.Serial(port, baudrate=baud, timeout=0.01)
        self.last_sample: Optional[SensorSample] = None

    def read_latest(self) -> Optional[SensorSample]:
        """Drain available serial lines briefly and return the newest valid sample."""
        deadline = time.time() + (0.60 if self.last_sample is None else 0.015)
        while time.time() < deadline:
            if self.last_sample is not None and not getattr(self.serial, "in_waiting", 0):
                break
            raw = self.serial.readline().decode("utf-8", errors="ignore").strip()
            if not raw:
                continue
            try:
                payload = json.loads(raw)
            except json.JSONDecodeError:
                continue
            if "error" in payload or "status" in payload:
                print(f"Arduino: {payload}")
                continue
            try:
                sample = SensorSample(
                    seq=int(payload.get("seq", 0)),
                    t_ms=int(payload.get("t_ms", 0)),
                    ax=float(payload.get("ax", 0.0)),
                    ay=float(payload.get("ay", 0.0)),
                    az=float(payload.get("az", 0.0)),
                    gx=float(payload.get("gx", 0.0)),
                    gy=float(payload.get("gy", 0.0)),
                    gz=float(payload.get("gz", 0.0)),
                    source="arduino_usb",
                )
            except (TypeError, ValueError):
                continue
            self.last_sample = sample
        return self.last_sample


class MockSensor:
    """Fallback sensor source for software-only connectivity checks."""

    def __init__(self) -> None:
        self.seq = 0

    def read_latest(self) -> SensorSample:
        self.seq += 1
        now_ms = int(time.time() * 1000)
        phase = self.seq / 9.0
        return SensorSample(
            seq=self.seq,
            t_ms=now_ms,
            ax=0.02 * math.sin(phase) + random.gauss(0, 0.015),
            ay=0.02 * math.cos(phase / 2.0) + random.gauss(0, 0.015),
            az=1.0 + random.gauss(0, 0.02),
            gx=random.gauss(0, 0.8),
            gy=random.gauss(0, 0.8),
            gz=random.gauss(0, 0.8),
            source="mock_sensor",
        )


def list_ports() -> None:
    try:
        import serial.tools.list_ports  # type: ignore
    except ImportError as exc:
        raise SystemExit("Install pyserial first: python -m pip install pyserial") from exc

    ports = list(serial.tools.list_ports.comports())
    if not ports:
        print("No serial ports found.")
        return
    for port in ports:
        print(f"{port.device}\t{port.description}")


def post_json(url: str, payload: dict[str, Any], timeout: float = 2.0) -> tuple[bool, str]:
    """Send one labelled JSON request to the Raspberry Pi ingest endpoint."""
    data = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return True, response.read().decode("utf-8", errors="ignore")
    except (urllib.error.URLError, TimeoutError) as exc:
        return False, str(exc)


def mode_delay(mode: str, rate: float, elapsed: float) -> float:
    """Return the delay before the next request for each traffic profile."""
    if mode == "normal":
        jitter = random.uniform(-0.035, 0.035)
        return max(0.02, (1.0 / rate) + jitter)
    if mode == "burst":
        in_burst = int(elapsed // 8) % 2 == 0
        effective_rate = rate if in_burst else max(1.5, rate / 7.0)
        return max(0.015, 1.0 / effective_rate + random.uniform(-0.02, 0.02))
    if mode == "attack_like":
        return max(0.008, 1.0 / rate + random.uniform(-0.006, 0.006))
    raise ValueError(f"Unknown mode: {mode}")


def run_gateway(args: argparse.Namespace) -> int:
    """Run a single normal, burst or attack-like traffic session."""
    if args.list_ports:
        list_ports()
        return 0

    if args.mock_sensor:
        reader: Any = MockSensor()
    else:
        if not args.serial:
            raise SystemExit("Pass --serial COMx, or use --mock-sensor for testing without hardware.")
        reader = ArduinoReader(args.serial, args.baud)

    ingest_url = args.pi.rstrip("/") + "/ingest"
    rate = args.rate if args.rate is not None else DEFAULT_RATES[args.mode]
    start = time.time()
    next_report = start
    sent = 0
    failed = 0

    print(f"Sending {args.mode} traffic to {ingest_url}")
    print(f"Rate target: {rate:.1f} requests/sec, duration: {args.duration:.1f}s")

    while time.time() - start < args.duration:
        sample = reader.read_latest()
        if sample is None:
            time.sleep(0.05)
            continue

        sent += 1
        payload = {
            "device": args.device_id,
            "client_role": "laptop_gateway",
            "label": args.mode,
            "scenario_id": args.scenario_id,
            "request_seq": sent,
            "client_ts": time.time(),
            "sensor": sample.to_dict(),
        }
        ok, message = post_json(ingest_url, payload)
        if not ok:
            failed += 1
            if failed <= 3:
                print(f"Request failed: {message}")

        now = time.time()
        if now >= next_report:
            print(f"{args.mode}: sent={sent} failed={failed}")
            next_report = now + 5

        time.sleep(mode_delay(args.mode, rate, time.time() - start))

    print(f"Finished. sent={sent} failed={failed}")
    return 0 if failed == 0 else 1


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Arduino/laptop gateway traffic generator")
    parser.add_argument("--pi", default="http://192.168.1.187:8000", help="Pi server base URL")
    parser.add_argument("--serial", help="Arduino serial port, e.g. COM4 or /dev/ttyACM0")
    parser.add_argument("--baud", type=int, default=115200)
    parser.add_argument("--mock-sensor", action="store_true", help="Generate fake IMU readings")
    parser.add_argument("--list-ports", action="store_true", help="List serial ports and exit")
    parser.add_argument("--mode", choices=sorted(DEFAULT_RATES), default="normal")
    parser.add_argument("--rate", type=float, help="Override request rate")
    parser.add_argument("--duration", type=float, default=60.0)
    parser.add_argument("--device-id", default="laptop_gateway")
    parser.add_argument("--scenario-id", default=time.strftime("run_%Y%m%d_%H%M%S"))
    return parser.parse_args(argv)


if __name__ == "__main__":
    raise SystemExit(run_gateway(parse_args(sys.argv[1:])))
